apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
spec:
  selector:
    app: nodejs-app
  ports:
    - protocol: TCP
      port: 80 # Port externe auquel accéder à votre application Node.js
      targetPort: 3000 # Port utilisé par votre application Node.js
  type: LoadBalancer # Type de service pour accéder à votre application depuis l'extérieur
